import { Button, Card, CardBody, CardHeader } from '@nextui-org/react'
import Head from 'next/head'

export default function Home() {
    return (
        <>
            <Head>
                <title>My Monorepo Web App</title>
                <meta name="description" content="Generated by create turbo" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1>Welcome to My Monorepo Web App</h1>
                <Card>
                    <CardHeader>Header</CardHeader>
                    <CardBody>
                        <Button color="primary">Click me</Button>
                    </CardBody>
                </Card>
            </main>
        </>
    )
}